### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by dehdox** [HermanFassett/youtube-scrape#21]
Hello, My heroku is crashing after you update the code. I noticed yours is as well.
Log and print.

 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/search?q=edm+2020&page=1"

![youtube](https://user-images.githubusercontent.com/20191049/86439982-fefddb80-bcdf-11ea-8e23-7effd6bdc2fa.jpg)

**Comment by HermanFassett** [comment]
Thanks for the issue, my initial thought is that deployed code is hitting limit of calls and I'm not handling it correctly in code, I didn't see any limits in development so I was hoping that wasn't the case. I'll check it out

**Comment by HermanFassett** [comment]
Apparently it's not hitting a limit, but some properties are undefined and cause the app to crash. I pushed a quick fix to dev branch that adds try/catch and logging, I also pushed those changes to the deployed heroku app, but not to master yet. I'll have to do further testing to see if I can find the underlying issue.

**Comment by vicwomg** [comment]
I get this on the master branch as well. Using the dev branch for now. 

Here is the stack trace

```
Listening on port 8080
/Users/vw/coding/youtube-scrape/scraper.js:34
                        sectionList.itemSectionRenderer.contents.forEach(content => {
                                                        ^

TypeError: Cannot read property 'contents' of undefined
    at /Users/vw/coding/youtube-scrape/scraper.js:34:57
    at Array.forEach (<anonymous>)
    at Request._callback (/Users/vw/coding/youtube-scrape/scraper.js:33:34)
    at Request.self.callback (/Users/vw/coding/youtube-scrape/node_modules/request/request.js:185:22)
    at Request.emit (events.js:316:20)
    at Request.<anonymous> (/Users/vw/coding/youtube-scrape/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:316:20)
    at IncomingMessage.<anonymous> (/Users/vw/coding/youtube-scrape/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:422:28)
    at IncomingMessage.emit (events.js:328:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-scrape@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-scrape@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vw/.npm/_logs/2020-07-25T08_20_18_028Z-debug.log
```

**Comment by angelboyes** [comment]
I also receive this problem


```
C:\Users\Fox\Desktop\nodejs\youtube-scrape\scraper.js:34
                        sectionList.itemSectionRenderer.contents.forEach(content => {
                                                        ^

TypeError: Cannot read property 'contents' of undefined
    at C:\Users\Fox\Desktop\nodejs\youtube-scrape\scraper.js:34:57
    at Array.forEach (<anonymous>)
    at Request._callback (C:\Users\Fox\Desktop\nodejs\youtube-scrape\scraper.js:33:34)
    at Request.self.callback (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\Fox\Desktop\nodejs\youtube-scrape\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-scrape@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-scrape@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fox\AppData\Roaming\npm-cache\_logs\2020-09-13T11_04_01_768Z-debug.log

```

**Comment by HermanFassett** [comment]
@angelboyes it would be good to see the data that caused this to happen, otherwise, I'm not sure how to fix this and I haven't been able to repro with the time I've had to spend on this. Again, for now, the dev branch will catch these errors and not cause a crash.
