### ISSUE TITLE
Module not found when deployed to heroku

### ISSUE THREAD

**Issue by krmkcbs** [HermanFassett/youtube-scrape#26]
`

2020-09-13T21:48:50.572029+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1137:30)

2020-09-13T21:48:50.572030+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

2020-09-13T21:48:50.572030+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:985:32)

2020-09-13T21:48:50.572030+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:878:14)

2020-09-13T21:48:50.572031+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {

2020-09-13T21:48:50.572031+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',

2020-09-13T21:48:50.572032+00:00 app[web.1]:   requireStack: [ '/app/server.js' ]

2020-09-13T21:48:50.572032+00:00 app[web.1]: }

2020-09-13T21:48:50.619741+00:00 heroku[web.1]: Process exited with status 1

2020-09-13T21:48:50.651818+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by krmkcbs** [comment]
issue fixed by typing heroku config:set NPM_CONFIG_PRODUCTION=false -a project_name
