### ISSUE TITLE
Heroku deploy application error (logs attached)

### ISSUE THREAD

**Issue by wackyapps** [HermanFassett/youtube-scrape#62]
Hi, 
I deployed on heroku which eventually end with Application Error. 

https://youtubescrapewk01.herokuapp.com/api/search?q=cricket

Below are logs

2021-03-01T13:25:28.766763+00:00 app[web.1]: requireStack: [ '/app/server.js' ]
2021-03-01T13:25:28.766764+00:00 app[web.1]: }
2021-03-01T13:25:28.782565+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T13:25:28.782906+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T13:25:28.788079+00:00 app[web.1]: npm ERR! youtube-scrape@0.1.5 start: `node server.js`
2021-03-01T13:25:28.788199+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T13:25:28.788360+00:00 app[web.1]: npm ERR!
2021-03-01T13:25:28.788472+00:00 app[web.1]: npm ERR! Failed at the youtube-scrape@0.1.5 start script.
2021-03-01T13:25:28.788598+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T13:25:29.809158+00:00 app[web.1]:
2021-03-01T13:25:29.809379+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T13:25:29.809503+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T13_25_28_789Z-debug.log
2021-03-01T13:25:29.859750+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T13:25:29.955283+00:00 heroku[web.1]: State changed from starting to crashed
2021-03-01T13:25:29.961322+00:00 heroku[web.1]: State changed from crashed to starting
2021-03-01T13:25:32.301267+00:00 heroku[web.1]: Starting process with command `npm start`
2021-03-01T13:25:34.729701+00:00 app[web.1]:
2021-03-01T13:25:34.729751+00:00 app[web.1]: > youtube-scrape@0.1.5 start /app
2021-03-01T13:25:34.729752+00:00 app[web.1]: > node server.js
2021-03-01T13:25:34.729752+00:00 app[web.1]:
2021-03-01T13:25:34.784708+00:00 app[web.1]: internal/modules/cjs/loader.js:883
2021-03-01T13:25:34.784709+00:00 app[web.1]: throw err;
2021-03-01T13:25:34.784709+00:00 app[web.1]: ^
2021-03-01T13:25:34.784710+00:00 app[web.1]:
2021-03-01T13:25:34.784710+00:00 app[web.1]: Error: Cannot find module 'express'
2021-03-01T13:25:34.784710+00:00 app[web.1]: Require stack:
2021-03-01T13:25:34.784711+00:00 app[web.1]: - /app/server.js
2021-03-01T13:25:34.784724+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2021-03-01T13:25:34.784724+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2021-03-01T13:25:34.784725+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-01T13:25:34.784725+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:88:18)
2021-03-01T13:25:34.784725+00:00 app[web.1]: at Object.<anonymous> (/app/server.js:1:17)
2021-03-01T13:25:34.784726+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-01T13:25:34.784726+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-01T13:25:34.784726+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-01T13:25:34.784726+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-01T13:25:34.784728+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
2021-03-01T13:25:34.784728+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-03-01T13:25:34.784728+00:00 app[web.1]: requireStack: [ '/app/server.js' ]
2021-03-01T13:25:34.784729+00:00 app[web.1]: }
2021-03-01T13:25:34.796350+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T13:25:34.796697+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T13:25:34.803405+00:00 app[web.1]: npm ERR! youtube-scrape@0.1.5 start: `node server.js`
2021-03-01T13:25:34.803564+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T13:25:34.803730+00:00 app[web.1]: npm ERR!
2021-03-01T13:25:34.803865+00:00 app[web.1]: npm ERR! Failed at the youtube-scrape@0.1.5 start script.
2021-03-01T13:25:34.804006+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T13:25:34.813728+00:00 app[web.1]:
2021-03-01T13:25:34.813932+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T13:25:34.814063+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T13_25_34_804Z-debug.log
2021-03-01T13:25:34.880432+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T13:25:34.983022+00:00 heroku[web.1]: State changed from starting to crashed
2021-03-01T13:25:36.112031+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=youtubescrapewk01.herokuapp.com request_id=dfba8eb5-1d00-44d8-8629-004a7167baa8 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:25:37.018870+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=youtubescrapewk01.herokuapp.com request_id=2398af6f-3cda-4607-9760-dce174febb02 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:26:51.220483+00:00 app[api]: Set NPM_CONFIG_PRODUCTION config vars by user fluttercaptain@gmail.com
2021-03-01T13:26:51.220483+00:00 app[api]: Release v4 created by user fluttercaptain@gmail.com
2021-03-01T13:26:51.435345+00:00 heroku[web.1]: State changed from crashed to starting
2021-03-01T13:26:54.894887+00:00 heroku[web.1]: Starting process with command `npm start`
2021-03-01T13:26:58.778943+00:00 app[web.1]:
2021-03-01T13:26:58.778966+00:00 app[web.1]: > youtube-scrape@0.1.5 start /app
2021-03-01T13:26:58.778967+00:00 app[web.1]: > node server.js
2021-03-01T13:26:58.778967+00:00 app[web.1]:
2021-03-01T13:26:58.958127+00:00 app[web.1]: internal/modules/cjs/loader.js:883
2021-03-01T13:26:58.958129+00:00 app[web.1]: throw err;
2021-03-01T13:26:58.958129+00:00 app[web.1]: ^
2021-03-01T13:26:58.958130+00:00 app[web.1]:
2021-03-01T13:26:58.958130+00:00 app[web.1]: Error: Cannot find module 'express'
2021-03-01T13:26:58.958130+00:00 app[web.1]: Require stack:
2021-03-01T13:26:58.958131+00:00 app[web.1]: - /app/server.js
2021-03-01T13:26:58.958132+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2021-03-01T13:26:58.958132+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2021-03-01T13:26:58.958133+00:00 app[web.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
2021-03-01T13:26:58.958133+00:00 app[web.1]: at require (internal/modules/cjs/helpers.js:88:18)
2021-03-01T13:26:58.958133+00:00 app[web.1]: at Object.<anonymous> (/app/server.js:1:17)
2021-03-01T13:26:58.958134+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-03-01T13:26:58.958134+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-03-01T13:26:58.958135+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
2021-03-01T13:26:58.958135+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-03-01T13:26:58.958135+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
2021-03-01T13:26:58.958136+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2021-03-01T13:26:58.958136+00:00 app[web.1]: requireStack: [ '/app/server.js' ]
2021-03-01T13:26:58.958137+00:00 app[web.1]: }
2021-03-01T13:26:58.987329+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-01T13:26:58.988129+00:00 app[web.1]: npm ERR! errno 1
2021-03-01T13:26:59.000112+00:00 app[web.1]: npm ERR! youtube-scrape@0.1.5 start: `node server.js`
2021-03-01T13:26:59.000375+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-01T13:26:59.000684+00:00 app[web.1]: npm ERR!
2021-03-01T13:26:59.000958+00:00 app[web.1]: npm ERR! Failed at the youtube-scrape@0.1.5 start script.
2021-03-01T13:26:59.001185+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-01T13:26:59.012722+00:00 app[web.1]:
2021-03-01T13:26:59.020058+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-01T13:26:59.020317+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-01T13_26_59_002Z-debug.log
2021-03-01T13:26:59.137435+00:00 heroku[web.1]: Process exited with status 1
2021-03-01T13:26:59.274898+00:00 heroku[web.1]: State changed from starting to crashed
2021-03-01T13:27:02.192254+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=youtubescrapewk01.herokuapp.com request_id=b1baf51d-20ed-4a3e-874e-894296050cf6 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:27:03.282548+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=youtubescrapewk01.herokuapp.com request_id=aa02dd04-1fb2-4dd0-8642-a4a4b8a8e50a fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:28:22.646338+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/search?pakistan" host=youtubescrapewk01.herokuapp.com request_id=b1070a14-305d-4dd3-95a1-6e824e7454eb fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:28:23.614559+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=youtubescrapewk01.herokuapp.com request_id=1d9a52ac-2ef0-458f-bc38-a15000acd434 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:40:03.835539+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/api/search?pakistan" host=youtubescrapewk01.herokuapp.com request_id=eba0c0e2-3d9d-4f18-886a-99c49449cdf2 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https
2021-03-01T13:40:05.148633+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=youtubescrapewk01.herokuapp.com request_id=a7265c0a-5678-4b50-81ea-a773a9fb2a09 fwd="110.36.201.208" dyno= connect= service= status=503 bytes= protocol=https

**Comment by HermanFassett** [comment]
Did you try this:
https://github.com/HermanFassett/youtube-scrape/issues/15#issuecomment-664034473

**Comment by wackyapps** [comment]
Thanks it worked. Sorry, I must have checked that. 

Appreciated.
